add_category_links:
  type: list
  default: "META, blank|MOST, self|PRIVACY, self"
  description:
    en: "Comma delimited in this order: tag, target<br><b>tag:</b> The tag which must match in the category description<br><b>Target:</b> blank = opens in a new tab, self = opens in the same tab"

fallback_to_parent_category:
  type: bool
  default: true
  description:
    en: "Use category links from parent category if child category links are empty"
